    [server]
    url          = "https://turees.zevtabs.mn/api/zogsoolSdkService"
    token        = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmRhZTc5MjZhNDI0OGYxMDY3N2ZiMyIsIm5lciI6ItCh0KXQlC3QuNC50L0g0LfQvtCz0YHQvtC-0LsiLCJiYWlndXVsbGFnaWluSWQiOiI2NzJkYWU3OTI2YTQyNDhmMTA2NzdmYjAiLCJpYXQiOjE3NzQzMjQ3MDB9.oFaWLynO6ZgexQzA-LsN0WfRRx_CBfPdFAKO9UnIxso"
    barilgiinId  = "672dae7926a4248f10677fb1"
    timeout_secs = 30
    retry_count  = 3

    [sdk]
    username                = "admin"
    heartbeat_interval_secs = 30
    connect_timeout_ms      = 5000
    max_connect_retries     = 5
    port                    = 37777
    org_name = "Төлбөртэй зогсоол"
    company_name = "ParkEase"

    [[cameras]]
    ip       = "172.16.18.123"
    password = "Admin123"
    http_port = 443
    gate = "entrance"
    sambar_type = "sambar"
    [[cameras]]
    ip       = "172.16.18.124"
    password = "Admin123"
    http_port = 443
    gate = "entrance"
    sambar_type = "sambar"
    [[cameras]]
    ip       = "172.16.18.125"
    password = "Admin123"
    http_port = 443
    gate = "exit"
    sambar_type = "sambar"
    [[cameras]]
    ip       = "172.16.18.126"
    password = "Admin123"
    http_port = 443
    gate = "exit"
    sambar_type = "sambar"
    
