    [server]
    url          = "https://turees.zevtabs.mn/api/zogsoolSdkService"
    token        = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OGNmN2U0MTU0ODBkYWQyY2I0ZmRlZSIsIm5lciI6ItCm0Y3Qs9C80Y3QtCIsImJhaWd1dWxsYWdpaW5JZCI6IjY1OGNmN2U0MTU0ODBkYWQyY2I0ZmRlYyIsImlhdCI6MTc3NTYzMTczM30.WDVlNPo-uYFJwbLAu1qCuJaIqkizIqD4u5EUctlE69U"
    barilgiinId  = "658d2a0488afdbb4feaf191e"
    timeout_secs = 30
    retry_count  = 3

    [sdk]
    username                = "admin"
    heartbeat_interval_secs = 30
    connect_timeout_ms      = 5000
    max_connect_retries     = 5
    port                    = 37777
    org_name = "Шөнийн зах"
    company_name = "ParkEase"

    [[cameras]]
    ip       = "192.168.111.5"
    password = "mongol123"
    http_port = 443
    gate = "entrance"
    sambar_type = "sambar" 
    [[cameras]]
    ip       = "192.168.111.4"
    password = "mongol123"
    http_port = 443
    gate = "exit"
    sambar_type = "sambar" 