    [server]
    url          = "https://turees.zevtabs.mn/api/zogsoolSdkService"
    token        = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OGFmZmVlODJjNGUxZTY2NjIyNzhlZSIsIm5lciI6ItCV0YDTqdOp0LvRgiIsImJhaWd1dWxsYWdpaW5JZCI6IjY5ODQwMmUyNmJiM2U5NGI1NjY1YmZlNCIsImlhdCI6MTc3NDQyNDA5MH0.fT-aSJJ_CI5Sc8QAzeBPc4WZM_6nXErB1PuYRnmaJLQ"
    barilgiinId  = "698402e26bb3e94b5665bfe5"
    timeout_secs = 30
    retry_count  = 3

    [sdk]
    username                = "admin"
    heartbeat_interval_secs = 30
    connect_timeout_ms      = 5000
    max_connect_retries     = 5
    port                    = 37777
    org_name = "Улаанбаатар буян"
    company_name = "ParkEase"

    [[cameras]]
    ip       = "172.16.19.195"
    password = "admin123"
    http_port = 80
    gate = "entrance"
    sambar_type = "sambar"
    
    [[cameras]]
    ip       = "172.16.19.196"
    password = "admin123"
    http_port = 443
    gate = "exit"
    sambar_type = "sambar"
    
